Updating

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -1,6 +1,9 @@
 name: Deploy CDK Infrastructure
 
 on:
+  push:
+    branches:
+      - main
   repository_dispatch:
     types:
       - trigger-cdk-deploy
@@ -15,7 +18,12 @@ jobs:
 
       - name: Download website artifact
         run: |
+          echo "Downloading dist.zip..."
           curl -L -o dist.zip https://github.com/jessekunze/angus-demo/releases/download/latest/dist.zip
+          if [ ! -s dist.zip ]; then
+            echo "Error: dist.zip is empty or missing!"
+            exit 1
+          fi
           unzip dist.zip -d dist/
 
       - name: Set up Node.js
@@ -25,6 +33,9 @@ jobs:
 
       - name: Install dependencies
         run: npm install
+
+      - name: Ensure target directory exists
+        run: mkdir -p ../angus-demo/dist
 
       - name: Deploy CDK stack
         env:
